r Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Oatmeal Cream Pie Book Club
email: abhisharma2@gmail.com
description: Book reviews and analysis from the Oatmeal Cream Pie Book Club
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://abhisharma2.github.io/ocpbc" # the base hostname & protocol for your site
twitter_username: ocpbc

# Build settings
markdown: kramdown
